### ISSUE TITLE
detect not exaclly object in moving camera

### ISSUE THREAD

**Issue by pvagithub** [Breakend/MotionDetection#1]
Hi guys,
I got your code, and try to detect my video example but it not working like expect.
I have been replace read section from video, read by read frame and pass to *_updateModel *_ function. I don't know have issues in during configuration and run program.
Thanks so much in advance.

**Comment by Breakend** [comment]
If you can describe the problem a bit more, I can maybe try to help, but as a disclaimer this wasn't meant to be production code, so it may take some hacking to get working properly on a different setup. If you mean that it's not isolating the moving object exactly, this is some limitation to the algorithm. Particularly with a moving camera it is difficult to gain reproducible results that perfectly isolate the moving objects.

**Comment by jrussino** [comment]
I'm also having trouble with this repository - the code compiles fine and I can run it on an image sequence, but it doesn't appear to label anything.

Can you provide the original image sequence that you used for testing?

**Comment by Breakend** [comment]
The labels should be a simple black and white mask. I submitted a writeup to arxiv on the implementation so I will add that to the Readme as soon as it's announced. The dataset we used is the University of Sherbrooke CDNet database as described here:

http://www.cv-foundation.org/openaccess/content_cvpr_workshops_2014/W12/papers/Wang_CDnet_2014_An_2014_CVPR_paper.pdf
